### ISSUE TITLE
PLUGIN_INITIALIZATION_ERROR | message needs to implement isReady or be an emitter

### ISSUE THREAD

**Issue by reedF** [deepstreamIO/deepstream.io-msg-amqp#48]
when I install amqp plugin and config it in config.yml like:
plugins:
  message:
    name: amqp
    options:
      host: ${AMQP_HOST}
      port: ${AMQP_PORT}
then start deepstream,deepstream can not start and run ,
how to fix it
 it show:

   __| | ___  ___ _ __  ___| |_ _ __ ___  __ _ _ __ ____
  / _` |/ _ \/ _ \ '_ \/ __| __| '__/ _ \/ _` | '_ ` _  \
 | (_| |  __/  __/ |_) \__ \ |_| | |  __/ (_| | | | | | |
  \__,_|\___|\___| .__/|___/\__|_|  \___|\__,_|_| |_| |_|
                 |_|
 =====================   starting   =====================
INFO | logger ready: std out/err
INFO | deepstream version: 3.1.0
INFO | configuration file loaded from conf\config.yml
INFO | library directory set to: D:\tools\deepstream.io-windows-3.1.0\lib
INFO | storage ready: no storage connector specified
INFO | cache ready: local cache
INFO | authenticationHandler ready: none
PLUGIN_INITIALIZATION_ERROR | message needs to implement isReady or be an emitter
[eval]:49329
      throw error
      ^

Error: message needs to implement isReady or be an emitter
    at new DependencyInitialiser ([eval]:49327:21)
    at _options.pluginTypes.forEach ([eval]:40901:27)
    at Array.forEach (native)
    at Deepstream._pluginInit ([eval]:40899:31)
    at Deepstream._transition ([eval]:40837:28)
    at DependencyInitialiser.loggerInitialiser.once ([eval]:40874:12)
    at DependencyInitialiser.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at DependencyInitialiser.emit (events.js:185:7)
    at DependencyInitialiser._emitReady ([eval]:49420:10)

**Comment by yasserf** [comment]
We no longer support msg plugins from 3.0 going forward. If you would like to connect to AMQP I would recommend writing a basic client to bridge deepstream to your qeueus
